import {
    AlertCircleIcon,
    Alert01Icon,
    ArchiveIcon,
    ArrowDataTransferHorizontalIcon,
    ArrowLeft01Icon,
    ArrowRight01Icon,
    Attachment01Icon,
    BadgeCheckIcon,
    BellIcon,
    Book01Icon,
    BookOpen01Icon,
    BoldIcon,
    Briefcase01Icon,
    Building01Icon,
    Building02Icon,
    DiamondIcon,
    Dumbbell01Icon,
    Calendar01Icon,
    Cancel01Icon,
    CancelCircleIcon,
    Chat01Icon,
    CheckmarkCircle02Icon,
    ChevronDownIcon,
    ChevronLeftIcon,
    ChevronRightIcon,
    ChevronUpIcon,
    ChevronsLeftIcon,
    CircleIcon,
    ClipboardIcon,
    Clock01Icon,
    CloudUploadIcon,
    CogIcon,
    Coins01Icon,
    CreditCardIcon,
    CropIcon,
    CubeIcon,
    CustomerSupportIcon,
    Download01Icon,
    EarthIcon,
    Edit02Icon,
    ExpandIcon,
    ExternalLinkIcon,
    FastForwardIcon,
    File01Icon,
    File02Icon,
    Folder01Icon,
    FolderAddIcon,
    FolderOpenIcon,
    FullScreenIcon,
    GitCompareIcon,
    GlobeIcon,
    Grid02Icon,
    HashIcon,
    HelpCircleIcon,
    HistoryIcon,
    Home01Icon,
    Hotel01Icon,
    HourglassIcon,
    IdCardIcon,
    Image01Icon,
    Image02Icon,
    ImageAdd01Icon,
    ImagesIcon,
    InboxIcon,
    InformationCircleIcon,
    ItalicIcon,
    LayerAddIcon,
    Link01Icon,
    LockIcon,
    Link02Icon,
    ListChecksIcon,
    ListIcon,
    ListOrderedIcon,
    LoaderCircleIcon,
    Logout01Icon,
    MagicWand01Icon,
    Mail01Icon,
    MailSend01Icon,
    Menu01Icon,
    MapsIcon,
    Medal01Icon,
    MedicalMaskIcon,
    Message01Icon,
    MessageSquareDotIcon,
    MinusIcon,
    MoreHorizontalIcon,
    Note01Icon,
    PaintBrush01Icon,
    PaletteIcon,
    Pdf01Icon,
    Pen01Icon,
    Pen02Icon,
    PencilEdit01Icon,
    PlayCircleIcon,
    PlaySquareIcon,
    PlusSignCircleIcon,
    PlusSignIcon,
    PowerOffIcon,
    QuoteUpIcon,
    ReceiptIcon,
    Recycle01Icon,
    Radio01Icon,
    Redo01Icon,
    Refresh01Icon,
    Restaurant01Icon,
    Robot01Icon,
    Search01Icon,
    SendIcon,
    Shield01Icon,
    ShieldCheckIcon,
    SmartPhone01Icon,
    SmileIcon,
    SquareIcon,
    SquareLock01Icon,
    Store01Icon,
    StrikethroughIcon,
    Target01Icon,
    Task01Icon,
    Tick02Icon,
    TickDouble01Icon,
    Time01Icon,
    TrashIcon,
    Undo02Icon,
    UndoIcon,
    UserAdd01Icon,
    UserCheck01Icon,
    UserCircleIcon,
    UserIcon,
    Upload01Icon,
    Video01Icon,
    Video02Icon,
    ViewIcon,
    VolumeHighIcon,
    VolumeMute01Icon,
    Wallet01Icon,
    Wrench01Icon,
    ZapIcon,
    ZoomInIcon,
} from "@hugeicons/core-free-icons"
import type {IconSvgElement} from "@hugeicons/react"

/**
 * Единая замена boxicons-имён (`bx-XXX`, без префикса `bx-`) на иконки Hugeicons.
 * Ключи совпадают со старыми именами классов, чтобы перенос вызовов был механическим.
 */
export const ICON_MAP = {
    "check": Tick02Icon,
    "file": File01Icon,
    "download": Download01Icon,
    "check-circle": CheckmarkCircle02Icon,
    "loader-alt": LoaderCircleIcon,
    "loader-circle": LoaderCircleIcon,
    "user": UserIcon,
    "x": Cancel01Icon,
    "credit-card": CreditCardIcon,
    "time-five": Clock01Icon,
    "image": Image01Icon,
    "support": CustomerSupportIcon,
    "chevron-down": ChevronDownIcon,
    "info-circle": InformationCircleIcon,
    "error-circle": AlertCircleIcon,
    "exclamation-circle": AlertCircleIcon,
    "edit": PencilEdit01Icon,
    "edit-alt": Edit02Icon,
    "book-open": BookOpen01Icon,
    "book": Book01Icon,
    "upload": Upload01Icon,
    "trash": TrashIcon,
    "plus": PlusSignIcon,
    "plus-circle": PlusSignCircleIcon,
    "paperclip": Attachment01Icon,
    "folder-open": FolderOpenIcon,
    "folder": Folder01Icon,
    "folder-plus": FolderAddIcon,
    "file-blank": File02Icon,
    "file-pdf": Pdf01Icon,
    "video": Video01Icon,
    "video-plus": Video02Icon,
    "send": SendIcon,
    "mail-send": MailSend01Icon,
    "chevron-up": ChevronUpIcon,
    "chevron-left": ChevronLeftIcon,
    "chevron-right": ChevronRightIcon,
    "chevrons-left": ChevronsLeftIcon,
    "x-circle": CancelCircleIcon,
    "message-dots": MessageSquareDotIcon,
    "message-square-dots": MessageSquareDotIcon,
    "message-alt-detail": Message01Icon,
    "chat": Chat01Icon,
    "lock-alt": SquareLock01Icon,
    "lock": LockIcon,
    "circle-dot": Radio01Icon,
    "check-shield": ShieldCheckIcon,
    "shield-check": ShieldCheckIcon,
    "shield": Shield01Icon,
    "user-plus": UserAdd01Icon,
    "user-check": UserCheck01Icon,
    "user-circle": UserCircleIcon,
    "transfer-alt": ArrowDataTransferHorizontalIcon,
    "transfer": ArrowDataTransferHorizontalIcon,
    "time": Time01Icon,
    "cloud-upload": CloudUploadIcon,
    "power-off": PowerOffIcon,
    "play-circle": PlayCircleIcon,
    "movie-play": PlaySquareIcon,
    "left-arrow-alt": ArrowLeft01Icon,
    "right-arrow-alt": ArrowRight01Icon,
    "arrow-back": ArrowLeft01Icon,
    "grid-alt": Grid02Icon,
    "globe": GlobeIcon,
    "planet": EarthIcon,
    "error": Alert01Icon,
    "cog": CogIcon,
    "briefcase": Briefcase01Icon,
    "bell": BellIcon,
    "map": MapsIcon,
    "link-external": ExternalLinkIcon,
    "link": Link01Icon,
    "link-alt": Link02Icon,
    "image-alt": Image02Icon,
    "image-add": ImageAdd01Icon,
    "images": ImagesIcon,
    "hourglass": HourglassIcon,
    "check-double": TickDouble01Icon,
    "building": Building01Icon,
    "buildings": Building02Icon,
    "wallet": Wallet01Icon,
    "show": ViewIcon,
    "search": Search01Icon,
    "receipt": ReceiptIcon,
    "phone": SmartPhone01Icon,
    "menu": Menu01Icon,
    "list-ul": ListIcon,
    "list-ol": ListOrderedIcon,
    "list-check": ListChecksIcon,
    "inbox": InboxIcon,
    "history": HistoryIcon,
    "revision": Undo02Icon,
    "help-circle": HelpCircleIcon,
    "fast-forward": FastForwardIcon,
    "envelope": Mail01Icon,
    "dots-horizontal-rounded": MoreHorizontalIcon,
    "wrench": Wrench01Icon,
    "undo": UndoIcon,
    "redo": Redo01Icon,
    "refresh": Refresh01Icon,
    "pencil": Pen01Icon,
    "pen": Pen02Icon,
    "palette": PaletteIcon,
    "brush": PaintBrush01Icon,
    "note": Note01Icon,
    "money": Coins01Icon,
    "medal": Medal01Icon,
    "hash": HashIcon,
    "clipboard": ClipboardIcon,
    "calendar": Calendar01Icon,
    "archive": ArchiveIcon,
    "zoom-in": ZoomInIcon,
    "volume-mute": VolumeMute01Icon,
    "volume-full": VolumeHighIcon,
    "target-lock": Target01Icon,
    "strikethrough": StrikethroughIcon,
    "smile": SmileIcon,
    "shape-square": SquareIcon,
    "area": SquareIcon,
    "circle": CircleIcon,
    "minus": MinusIcon,
    "magic-wand": MagicWand01Icon,
    "log-out": Logout01Icon,
    "lightning-charge": ZapIcon,
    "layer-plus": LayerAddIcon,
    "italic": ItalicIcon,
    "id-card": IdCardIcon,
    "home-alt": Home01Icon,
    "git-compare": GitCompareIcon,
    "fullscreen": FullScreenIcon,
    "expand-alt": ExpandIcon,
    "cube": CubeIcon,
    "crop": CropIcon,
    "bot": Robot01Icon,
    "bold": BoldIcon,
    "badge-check": BadgeCheckIcon,
    "recycle": Recycle01Icon,
    "diamond": DiamondIcon,
    "dumbbell": Dumbbell01Icon,
    "home": Home01Icon,
    "hotel": Hotel01Icon,
    "plus-medical": MedicalMaskIcon,
    "restaurant": Restaurant01Icon,
    "store": Store01Icon,
    "task": Task01Icon,
    "message-detail": Message01Icon,
    "paper-plane": SendIcon,
    "quote-alt-left": QuoteUpIcon,
} as const satisfies Record<string, IconSvgElement>

export type IconName = keyof typeof ICON_MAP

/** Снимает старый префикс `bx-`/`bx bx-` с динамически хранимых имён иконок (конфиги, ветвления). */
export function stripBx(name: string): IconName {
    return name.replace(/^bx bx-/, "").replace(/^bx-/, "") as IconName
}
